[project]
name = "podcast-app"
version = "0.1.0"
description = "A web application for creating podcasts"
requires-python = ">=3.14"
dependencies = [
    "litestar[jinja]==2.19.0",
    "uvicorn[standard]==0.40.0",
    "pydantic==2.12.5",
    "pydantic-settings==2.12.0",
    "sqlalchemy[asyncio]==2.0.45",
    "alembic==1.17.2",
    "asyncpg==0.31.0",
    "uvloop==0.22.1",
]

[dependency-groups]
dev = [
    "pytest>=9,<10",
    "pytest-asyncio>=1.3,<1.4",
    "coverage>=7.13,<7.14",
    "black>=25.1,<26.0",
    "ruff>=0.14,<0.15",
    "mypy>=0.19,<1.20",
    # pycharm requires:
    "setuptools<81.0",
    "pip<26",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.black]
line-length = 100
target-version = ["py314"]
